---
- name: play A
  hosts: localhost
  gather_facts: false
  vars:
    device: "Routers"

  tasks:
    - name: hello world
      debug:
        msg: "hello world"
    - name: print vars
      debug:
        var: device
    
    - name: Set Fact for source ip
      set_fact:
        src_ip: "testing set fact for source ip 10.2.2.2"

    - name: display set fact value
      debug:
        var: src_ip