---
- name: play A
  hosts: localhost
  gather_facts: false
  vars:
  # fixing the variable with Router,it's static
    # device_type: "Router"  
  #putting varaible within "{{}}" will make it dynamic and we can pass any variable value at runtime  
    device_type: "{{ nts }}"
    devices: 
      - "R1"
      - "R2"
      - "R3"
    devices_creds:
      user_name: "NetG"
      password: "India"
  tasks:
    - name: "1010 - OUTPUT DEVICE TYPE"
      debug:  
        var: device_type
  # We can directly pass variable in debug also and pass it directly into input as -e "nts=value" during run time 
      #  var: nts
      #  msg: "{{ nts }}"
    - name: "1020 - OUTPUT DEVICES DATA"
      debug:
        var: devices
    
    - name: "1030 - OUTPUT DEVICES CREDS"
      debug:
        var: devices_creds